<?php

/**
 * Implementation of hook_menu().
 */
function easymailing_menu() {
  $items['admin/settings/easymailing'] = array(
    'title' => 'Easy Mailing',
    'description' => 'Configurações do modulo Easy Mailing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easymailing_settings_form'),
    'access arguments' => array('easymailing settings'),
  );
  return $items;
}
/**
 * Implementation of hook_help();
 */
function easymailing_help($path='') {
  switch ($path):
    case "admin/help#easymailing":
   // case 'admin/settings/qq-campanhas':
      return "O módulo Easy Mailing possibilita gerar um formulario de cadastro da newsletter integrado com o sistema Easy Mailing da Dinamize.";
    break;
  endswitch;
  return '';

}
/**
 * Implementation of hook_perm()
 */
 function easymailing_perm(){
     return array('Administrar configurações');
 }

/**
 * Implementation of hook_form();
 */
function easymailing_settings_form() {
  $form['easymailing'] = array(
    '#title' => '',
    '#type' => 'textfield',
    '#description' => 'Digite somente números inteiros.',
    '#default_value' => variable_get('easymailing', 1),
  );
  $form[] = array(
    '#type' => 'submit',
    '#value' => 'Salvar configuração',
  );

  return $form;
}
/**
 * Implementation of hook_validate();
 */
function easymailing_settings_form_validate($form, &$form_state) {
    $args = func_get_args();
    foreach($args[1]['values'] as $var_name => $value):
        switch($var_name):
            case 'easymailing':
            break;
        endswitch;
    endforeach;
}
 /**
  * Função de apoio que centraliza as mensagens de erro
  * usada no easymailing_settings_form_validate
  * @param $field_name - field name with error
  * @param $form - form object
  */
function _message_to(){
    $p = func_get_args();
    $type_message = 'error';
    if(is_array($p[0])):
        array_unshift($p,'first');
        $type_message = 'ok';
    endif;
    if(!isset($p[1])) return false;

    $messages = array(
      'easymailing' => " " ,
      'first'       => "Configuração salva com sucesso!"
    );
    drupal_set_message($messages[$p[0]],$type_message);
}

/**
 * Implementation of hook_nodeapi();
 */
function easymailing_nodeapi(&$node,$op,$a3=NULL,$a4=NULL){
    if($node->type == ''):
        switch($op):
            case 'validate':

            break;
            case 'insert':
            break;
        endswitch;
    endif;
}

